DataBaseTest/Controllers/TestController.cs
using DataBaseTest.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySql.Data.MySqlClient.Memcached;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Collections;
using DataBaseTest.Models.Dto;

namespace DataBaseTest.Controllers
{
    public class TestController : Controller
    {
        // GET: TestController
        /// <summary>
        /// 用於顯示使用者資料
        /// </summary>
        /// <param name="_ID"></param>
        /// <returns></ returns>
        public async Task<IActionResult> Index()
        {

            using HttpClient client = new()
            {
                BaseAddress = new Uri("http://localhost:5142/api/Database/")
            };
            

            UserDtoModel? user = new UserDtoModel();
            
            
            user = await client.GetFromJsonAsync<UserDtoModel>("");
            
            return View(user);

        }
        /// <summary>
        /// 搜尋使用者資料
        /// </summary>
        /// <param name="UserId"></param>
        /// <returns></returns>
        [HttpPost, ActionName("index")]
        public async Task<IActionResult> User(UserDtoModel userDtoModel)
        {

            using HttpClient client = new()
            {
                BaseAddress = new Uri("http://localhost:5142/api/Database/")
            };
            try
            {
                UserDtoModel? user = new UserDtoModel();

                // User? user = new User();
                //if (UserId == null)
                //{
                //    UserId = 0;
                //}
                //else
                //{
                //     user.UserId= (int)UserId;
                //}


                //if (UserName == null)
                //    user.UserName = "*";
                //else
                //{
                //    user.UserName = UserName;
                //}
                //if (UserEmail == null)
                //{
                //    user.UserEmail = "*";
                //}

                //else
                //{
                //    user.UserEmail = UserEmail;
                //}

                //user = await client.GetFromJsonAsync<User>((user.UserId.ToString() + "," + user.UserName + "," + user.UserEmail));
                user = await client.GetFromJsonAsync<UserDtoModel>("");//userDtoModel;//

                return View(user);
            }
            catch (Exception ex)
            {

                return Content(ex.ToString());
            }

        }
        /// <summary>
        /// 開啟編輯頁面
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// 接收資料後put至api
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost, ActionName("create")]   // 把下面的動作名稱，改成 CreateConfirm 試試看？
        [ValidateAntiForgeryToken]   // 避免CSRF攻擊。在FormTagHelper - 如果有寫 action屬性、或是Method = Get就會啟動此功能。設定為true。
                                     // https://docs.microsoft.com/zh-tw/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.formtaghelper
        public async Task<IActionResult> CreateConfirm(UserModel user)
        {
            using HttpClient client = new()
            {
                BaseAddress = new Uri("http://localhost:5142/api/Database/")
            };  

            HttpResponseMessage response = await client.PostAsJsonAsync("", user);
            return View(user);
        }



        /// <summary>
        /// 刪除確認頁面
        /// </summary>
        /// <param name="_ID"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int? _ID)    // 網址 http://xxxxxx/Test/Delete?_ID=1 
        {
            using HttpClient client = new()
            {
                BaseAddress = new Uri("http://localhost:5142/api/Database/")
            };
            if (_ID == null)
            {   // 沒有輸入文章編號（_ID），就會報錯 - Bad Request
                //return new StatusCodeResult((int)System.Net.HttpStatusCode.BadRequest);
                return Content(" 沒有輸入文章編號（_ID）");
            }

            // 使用上方 Details動作的程式，先列出這一筆的內容，給使用者確認
            UserModel? user = await client.GetFromJsonAsync<UserModel>(_ID.ToString()+",*,*");

            if (user == null||_ID==9999)
            {   // 找不到這一筆記錄
                // return NotFound(); 
                return Content(" 找不到這一筆記錄！");
            }
            else
            {
                return View(user);
            }
        }
        /// <summary>
        /// 透過api做刪除
        /// </summary>
        /// <param name="_ID"></param>
        /// <returns></returns>
        //== 真正刪除這一筆，並回寫資料庫 ===============
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int _ID)
        {

            if (ModelState.IsValid)   // ModelState.IsValid，通過表單驗證（Server-side validation）需搭配 Model底下類別檔的 [驗證]
            {


                using HttpClient client = new()
                {
                    BaseAddress = new Uri("http://localhost:5142/api/Database/")
                };

                UserModel? user = await client.GetFromJsonAsync<UserModel>(_ID.ToString()+",*,*");

                if (user == null)
                {   // 找不到這一筆記錄
                    return Content(" 刪除時，找不到這一筆記錄！");
                }

                else
                {
                    HttpResponseMessage response = await client.DeleteAsync($"{_ID}");
                    return Content(" 刪除一筆記錄，成功！");
                }   // 刪除成功後，出現訊息（字串）。


            }
            else
            {   // 搭配 ModelState.IsValid，如果驗證沒過，就出現錯誤訊息。
                ModelState.AddModelError("Value1", " 自訂錯誤訊息(1) ");
                ModelState.AddModelError("Value2", " 自訂錯誤訊息(2) ");
                return View();   // 將錯誤訊息，返回並呈現在「刪除」的檢視畫面上
            }
        }

        /// <summary>
        /// 編輯輸入頁面
        /// </summary>
        /// <param name="_ID"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Edit(int? _ID = 1)
        {
            using HttpClient client = new()
            {
                BaseAddress = new Uri("http://localhost:5142/api/Database/")
            };
            if (_ID == null||_ID==9999)
            {
                return Content("請輸入 正確的 ID 編號");
            }


            UserModel? user = await client.GetFromJsonAsync<UserModel>(_ID.ToString()+",*,*");
            if (user == null)
            {
                return Content("找不到任何記錄");
            }
            else
            {
                return View(user);
            }
        }

        /// <summary>
        /// 透過api編輯資料
        /// </summary>
        /// <param name="_user"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Edit")]


        public async Task<IActionResult> EditConfirm([Bind("UserId, UserName, UserPassWord, UserEmail")] UserModel _user)
        {
            using HttpClient client = new()
            {
                BaseAddress = new Uri("http://localhost:5142/api/Database/")
            };






            if (ModelState.IsValid)   // ModelState.IsValid，通過表單驗證（Server-side validation）需搭配 Model底下類別檔的 [驗證]
            {

                HttpResponseMessage response = await client.PutAsJsonAsync<UserModel>(_user.UserId.ToString(), _user);
                return Content(" *** 完成 *** ");
                //return RedirectToAction(nameof(List));  // 提升程式的維護性，常用在"字串"上。
            }
            else
            {
                //return View(_userTable);  // 若沒有修改成功，則列出原本畫面
                return Content(" *** 更新失敗！！**");
            }

        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? _ID )
        {
            using HttpClient client = new()
            {
                BaseAddress = new Uri("http://localhost:5142/api/Database/")
            };
            if (_ID == null)
            {
                return Content("請輸入 _ID 編號");
            }


            UserDtoModel? user = await client.GetFromJsonAsync<UserDtoModel>(_ID.ToString());
            if (user == null)
            {
                return Content("找不到任何記錄");
            }
            else
            {
                return View(user);
            }
        }
        public ActionResult IndexTest()
        {
            DateTime date = DateTime.Now;
            ViewBag.Date = date;
            UserModel data = new UserModel();
            data.UserEmail = "123";
            data.UserPassWord = "123";
            data.UserName = "123";
            data.UserId = 1;
            return View(data);
        }   
    }

}

DataBaseTest/Views/Home/Create.cshtml
@model DataBaseTest.Models.UserModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserPassWord" class="control-label"></label>
                <input asp-for="UserPassWord" class="form-control" />
                <span asp-validation-for="UserPassWord" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserEmail" class="control-label"></label>
                <input asp-for="UserEmail" class="form-control" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DataBaseTest/Views/Home/Delete.cshtml
@model DataBaseTest.Models.UserModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserPassWord)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserPassWord)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserEmail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" name="_ID" value=@Html.DisplayFor(model => model.UserId) />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="List">Back to List</a>
    </form>
</div>

DataBaseTest/Views/Home/Edit.cshtml
@model DataBaseTest.Models.UserModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @*在View中，如果有載入_ValidationScriptsPartial.cshtml的話，可以使用此方式顯示驗證失敗的錯誤訊息*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                       <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
@*                <input asp-for="UserId" class="form-control" />   <!-- 預設的檢視畫面，產生的欄位 -->*@
                <font color="red"><h3> @Html.DisplayFor(model => model.UserId) </h3></font>
                <!-- 以前 .NET完整版- MVC5 的寫法 / 呈現這筆記錄的ID（主索引鍵）**** -->


                <input asp-for="UserId"  type="hidden" />

                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserPassWord" class="control-label"></label>
                <input asp-for="UserPassWord" class="form-control" />
                <span asp-validation-for="UserPassWord" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserEmail" class="control-label"></label>
                <input asp-for="UserEmail" class="form-control" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>
@*載入方式*@
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DataBaseTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <a asp-controller="Test" asp-action="index" >透過Api連接資料庫</a>
    <a asp-action="list" >直接連接資料庫</a>
</div>

DataBaseTest/Views/Home/IndexTest.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = null;

    DateTime dateT = ViewBag.Date;
    var student = ViewBag. UserModel;
    var list = ViewBag.List;
}

@model DataBaseTest.Models.UserModel

<form>
    <div class="form-group">
        <label for="exampleInputEmail1">id</label>
        <input type="text" class="form-control" id="exampleInputid" placeholder="Enter id" value="@Model.UserId">
        <small id="emailHelp" class="form-text text-muted">請輸入數字</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">姓名</label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Password" value="@Model.UserName">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter email" value="@Model.UserEmail">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">密碼</label>
        <input type="text" class="form-control" id="exampleInputPassword" placeholder="Enter email" value= date >
    </div>
    <button type="submit" class="btn btn-primary">確定</button>
</form>

DataBaseTest/Views/Home/List.cshtml
@model IEnumerable<DataBaseTest.Models.UserModel>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserPassWord)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserPassWord)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserEmail)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  @_ID=item.UserId }) |
                @Html.ActionLink("Delete", "Delete", new {@_ID=item.UserId  })
            </td>
        </tr>
}
    </tbody>
</table>